AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patientcheckout

  Sample SAM Template for patientcheckout

Globals:
  Function:
      Runtime: java17
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientcheckoutTopic
Resources:
  PatientCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
  PatientcheckoutTopic:
    Type: AWS::SNS::Topic
  PatientcheckoutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.sk.aws.lambda.s3sns.PatientCheckoutLambda::handleRequest 
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
           BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy: 
           TopicName: !GetAtt PatientcheckoutTopic.TopicName

  BillManagementFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patientcheckout
      Handler: com.sk.aws.lambda.s3sns.BillManagementLambda::handleRequest
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientcheckoutTopic